// <auto-generated />
using System;
using Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(OpenVidContext))]
    [Migration("20240907223937_TagImplications")]
    partial class TagImplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PermissionGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Database.Models.PermissionGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PermissionGroup");
                });

            modelBuilder.Entity("Database.Models.Ratings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Database.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Database.Models.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RoleClaims_RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Database.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Database.Models.TagImplication", b =>
                {
                    b.Property<int>("FromId")
                        .HasColumnType("int")
                        .HasColumnName("FromId");

                    b.Property<int>("ToId")
                        .HasColumnType("int")
                        .HasColumnName("ToId");

                    b.HasKey("FromId", "ToId");

                    b.HasIndex("ToId");

                    b.ToTable("TagImplication");
                });

            modelBuilder.Entity("Database.Models.TagType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("ShowDescription")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TagType");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Database.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserClaims_UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Database.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserLogins_UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Database.Models.UserPermission", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("Database.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Database.Models.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("Database.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time(0)");

                    b.Property<string>("MetaText")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int")
                        .HasColumnName("RatingID");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Database.Models.VideoEncodeQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Encoder")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("InputDirectory")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVertical")
                        .HasColumnType("bit");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PlaybackFormat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<double>("Quality")
                        .HasColumnType("float");

                    b.Property<string>("RenderSpeed")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("VideoFormat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoEncodeQueue");
                });

            modelBuilder.Entity("Database.Models.VideoSegmentQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoSegmentQueue");
                });

            modelBuilder.Entity("Database.Models.VideoSegmentQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArgInputFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArgInputFolder")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArgLanguage")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ArgStream")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ArgStreamFolder")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArgStreamId")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    b.Property<int>("VideoSegmentQueueId")
                        .HasColumnType("int")
                        .HasColumnName("VideoSegmentQueueId");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("VideoSegmentQueueId");

                    b.ToTable("VideoSegmentQueueItem");
                });

            modelBuilder.Entity("Database.Models.VideoSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("MD5");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoSource");
                });

            modelBuilder.Entity("Database.Models.VideoTag", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.HasKey("VideoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("VideoTag");
                });

            modelBuilder.Entity("Database.Models.Permission", b =>
                {
                    b.HasOne("Database.Models.PermissionGroup", "PermissionGroup")
                        .WithMany("Permission")
                        .HasForeignKey("PermissionGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Permission_PermissionGroup");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Database.Models.RoleClaim", b =>
                {
                    b.HasOne("Database.Models.Role", "Role")
                        .WithMany("RoleClaim")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Database.Models.Tag", b =>
                {
                    b.HasOne("Database.Models.TagType", "TypeNavigation")
                        .WithMany("Tag")
                        .HasForeignKey("Type")
                        .HasConstraintName("FK_Tag_TagType");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("Database.Models.TagImplication", b =>
                {
                    b.HasOne("Database.Models.Tag", "From")
                        .WithMany("TagImplicationFrom")
                        .HasForeignKey("FromId")
                        .IsRequired()
                        .HasConstraintName("FK_TagImplication_FromId");

                    b.HasOne("Database.Models.Tag", "To")
                        .WithMany("TagImplicationTo")
                        .HasForeignKey("ToId")
                        .IsRequired()
                        .HasConstraintName("FK_TagImplication_ToId");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Database.Models.UserClaim", b =>
                {
                    b.HasOne("Database.Models.User", "User")
                        .WithMany("UserClaim")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.UserLogin", b =>
                {
                    b.HasOne("Database.Models.User", "User")
                        .WithMany("UserLogin")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.UserPermission", b =>
                {
                    b.HasOne("Database.Models.Permission", "Permission")
                        .WithMany("UserPermission")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPermission_Permission");

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("UserPermission")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPermission_User");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.UserRole", b =>
                {
                    b.HasOne("Database.Models.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.UserToken", b =>
                {
                    b.HasOne("Database.Models.User", "User")
                        .WithMany("UserToken")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.Video", b =>
                {
                    b.HasOne("Database.Models.Ratings", "Rating")
                        .WithMany("Video")
                        .HasForeignKey("RatingId")
                        .HasConstraintName("FK__Video__RatingID__5CD6CB2B");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Database.Models.VideoEncodeQueue", b =>
                {
                    b.HasOne("Database.Models.Video", "Video")
                        .WithMany("VideoEncodeQueue")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoEncodeQueue_Video");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Database.Models.VideoSegmentQueue", b =>
                {
                    b.HasOne("Database.Models.Video", "Video")
                        .WithMany("VideoSegmentQueue")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoSegmentQueue_Video");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Database.Models.VideoSegmentQueueItem", b =>
                {
                    b.HasOne("Database.Models.Video", "Video")
                        .WithMany("VideoSegmentQueueItem")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoSegmentQueueItem_Video");

                    b.HasOne("Database.Models.VideoSegmentQueue", "VideoSegmentQueue")
                        .WithMany("VideoSegmentQueueItem")
                        .HasForeignKey("VideoSegmentQueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoSegmentQueueItem_VideoSegmentQueue");

                    b.Navigation("Video");

                    b.Navigation("VideoSegmentQueue");
                });

            modelBuilder.Entity("Database.Models.VideoSource", b =>
                {
                    b.HasOne("Database.Models.Video", "Video")
                        .WithMany("VideoSource")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoSource_Video");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Database.Models.VideoTag", b =>
                {
                    b.HasOne("Database.Models.Tag", "Tag")
                        .WithMany("VideoTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoTag_Tag");

                    b.HasOne("Database.Models.Video", "Video")
                        .WithMany("VideoTag")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoTag_VideoID");

                    b.Navigation("Tag");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Database.Models.Permission", b =>
                {
                    b.Navigation("UserPermission");
                });

            modelBuilder.Entity("Database.Models.PermissionGroup", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Database.Models.Ratings", b =>
                {
                    b.Navigation("Video");
                });

            modelBuilder.Entity("Database.Models.Role", b =>
                {
                    b.Navigation("RoleClaim");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Database.Models.Tag", b =>
                {
                    b.Navigation("TagImplicationFrom");

                    b.Navigation("TagImplicationTo");

                    b.Navigation("VideoTag");
                });

            modelBuilder.Entity("Database.Models.TagType", b =>
                {
                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Navigation("UserClaim");

                    b.Navigation("UserLogin");

                    b.Navigation("UserPermission");

                    b.Navigation("UserRole");

                    b.Navigation("UserToken");
                });

            modelBuilder.Entity("Database.Models.Video", b =>
                {
                    b.Navigation("VideoEncodeQueue");

                    b.Navigation("VideoSegmentQueue");

                    b.Navigation("VideoSegmentQueueItem");

                    b.Navigation("VideoSource");

                    b.Navigation("VideoTag");
                });

            modelBuilder.Entity("Database.Models.VideoSegmentQueue", b =>
                {
                    b.Navigation("VideoSegmentQueueItem");
                });
#pragma warning restore 612, 618
        }
    }
}
